language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"

branches:
  only:
    - master
    - develop

install:
  - composer install

script:
  - php test.php

matrix:
  allow_failures:
    - php: "hhvm"
    - php: "5.3"

